#!/usr/bin/env bash
# Configuring nginx server to have a custom 404 page that contains the string "Ceci n'est pas une page".
ERREUR="error_page 404 /custom_404.html;\n\\t location = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\t internal; \n\t}\n"
PATTERN="#error_page 404 /404.html;"
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.google.com permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "s@$PATTERN@$ERREUR@" /etc/nginx/sites-available/default 
sudo nginx -t
sudo service nginx restart
